app/models.py
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime
from . import db

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index =True)
    firstname = db.Column(db.String(255))
    lastname = db.Column(db.String(255))
    email = db.Column(db.String(255),unique = True,index = True)
    bio = db.Column(db.String(5000))
    profile_pic_path = db.Column(db.String)
    pass_secure = db.Column(db.String(255))
    date_joined = db.Column(db.DateTime,default=datetime.utcnow)

    pitches = db.relationship('Pitch',backref = 'user',lazy = "dynamic")

    comments = db.relationship('Comment',backref = 'user',lazy = "dynamic")

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self,password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    def __repr__(self):
        return f'User {self.username}'

class Pitch(db.Model):
    __tablename__ = 'pitches'

    id = db.Column(db.Integer,primary_key = True)
    pitch_title = db.Column(db.String)
    pitch_content = db.Column(db.String(1000))
    category = db.Column(db.String)
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))
    likes = db.Column(db.Integer)
    dislikes = db.Column(db.Integer)

    comments = db.relationship('Comment',backref =  'pitch_id',lazy = "dynamic")

    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_pitches(cls,category):
        pitches = Pitch.query.filter_by(category=category).all()
        return pitches

    @classmethod
    def get_pitch(cls,id):
        pitch = Pitch.query.filter_by(id=id).first()

        return pitch

class Comment(db.Model):
    __tablename__ = 'comments'

    id = db.Column(db.Integer,primary_key = True)
    comment = db.Column(db.String(1000))
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))
    pitch = db.Column(db.Integer,db.ForeignKey("pitches.id"))

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls,pitch):
        comments = Comment.query.filter_by(pitch_id=pitch).all()
        return comments

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,SelectField
from wtforms.validators import Required

class PitchForm(FlaskForm):

    title = StringField('Pitch title',validators=[Required()])
    text = TextAreaField('Text',validators=[Required()])
    category = SelectField('Type',choices=[('interview','Interview pitch'),('product','Product pitch'),('promotion','Promotion pitch')],validators=[Required()])
    submit = SubmitField('Submit')

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Bio.',validators = [Required()])
    submit = SubmitField('Submit')

class CommentForm(FlaskForm):
    text = TextAreaField('Leave a comment:',validators=[Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail



bootstrap = Bootstrap()
db = SQLAlchemy()
mail = Mail()
photos = UploadSet('photos',IMAGES)

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    # confiure UploadSet
    configure_uploads(app,photos)

    return app
    

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from ..models import User,Pitch,Comment
from .. import db,photos
from .forms import UpdateProfile,PitchForm,CommentForm
from flask_login import login_required,current_user
import datetime

@main.route('/')
def index():

    title = 'Welcome to Pitches Site'
    interview_piches = Pitch.get_pitches('interview')
    product_piches = Pitch.get_pitches('product')
    promotion_pitches = Pitch.get_pitches('promotion')

    return render_template('index.html',title = title, interview = interview_piches, product = product_piches, promotion = promotion_pitches)

@main.route('/user/<name>')
def profile(name):
    user = User.query.filter_by(username = name).first()
    pitches_count = Pitch.count_pitches(name)
    user_joined = user.date_joined.strftime('%b %d, %Y')

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user,pitches = pitches_count,date = user_joined)

@main.route('/user/<name>/update',methods = ['GET','POST'])
@login_required
def update_profile(name):
    user = User.query.filter_by(username = name).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',name=user.username))

    return render_template('profile/update.html',form = form)

@main.route('/user/<name>/update/pic',methods= ['POST'])
@login_required
def update_pic(name):
    user = User.query.filter_by(username = name).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',name=name))

@main.route('/pitch/new', methods = ['GET','POST'])
@login_required
def add_pitch():
    pitch_form = PitchForm()
    if pitch_form.validate_on_submit():
        title = pitch_form.title.data
        pitch = pitch_form.text.data
        category = pitch_form.category.data
        new_pitch = Pitch(pitch_title=title,pitch_content=pitch,category=category,user=current_user,likes=0,dislikes=0)
        new_pitch.save_pitch()
        return redirect(url_for('main.index'))
    return render_template('new_pitch.html',title = title,pitch_form=pitch_form )

@main.route('/pitches/interview_pitches')
def interview():

    pitches = Pitch.get_pitches('interview')

    return render_template("interview.html", pitches = pitches)

@main.route('/pitches/product_pitches')
def product():

    pitches = Pitch.get_pitches('product')

    return render_template("product.html", pitches = pitches)

@main.route('/pitches/promotion_pitches')
def promotion():

    pitches = Pitch.get_pitches('promotion')

    return render_template("promotion.html", pitches = pitches)

@main.route('/pitch/<int:id>', methods = ['GET','POST'])
def pitch(id):
    pitch = Pitch.get_pitch(id)
    posted_date = pitch.posted.strftime('%b %d, %Y')

    if request.args.get("like"):
        pitch.likes = pitch.likes + 1

        db.session.add(pitch)
        db.session.commit()

        return redirect("/pitch/{pitch_id}".format(pitch_id=pitch.id))

    elif request.args.get("dislike"):
        pitch.dislikes = pitch.dislikes + 1

        db.session.add(pitch)
        db.session.commit()

        return redirect("/pitch/{pitch_id}".format(pitch_id=pitch.id))

    comment_form = CommentForm()
    if comment_form.validate_on_submit():
        comment = comment_form.text.data

        new_comment = Comment(comment = comment,user = current_user,pitch_id = pitch)

        new_comment.save_comment()


    comments = Comment.get_comments(pitch)

    return render_template("pitch.html", pitch = pitch, comment_form = comment_form, comments = comments, date = posted_date)

@main.route('/user/<name>/pitches')
def user_pitches(name):
    user = User.query.filter_by(username=name).first()
    pitches = Pitch.query.filter_by(user_id = user.id).all()
    
    return render_template("profile/pitches.html", user=user,pitches=pitches)

app/templates/base.html
{% extends 'bootstrap/base.html'%}

<!-- Navbar block  -->
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

{%block styles %}
  {{super()}}
  <link href="https://fonts.googleapis.com/css?family=Indie+Flower|Ranga" rel="stylesheet">
 
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}
<!-- Styles block -->


{%block content%}
<div class="container" style= "font-family: 'Cormorant Upright', serif; padding-bottom: 20px; padding-top: 20px;">
    <div class="row ">
        <div class="col-md-6 mx-auto text-center">
            <div class="well well-lg">
                <h3>Interview Pitches</h3>
                <p>Want to ace an interview in just a few words, welcome.</p>
                <a href="{{url_for('main.interview')}}" class="btn btn-primary -center">View</a>
            </div>
        </div>
        
    </div>
    <hr  style="border: 2px solid gray;">
    <div class="row">
        <div class="col-md-6 mx-auto text-center">
            <div class="well well-lg">
                <h3>Product Pitches</h3>
                <p>Want to talk about your products, you're in the right place.</p>
                <a href="{{url_for('main.product')}}" class="btn btn-primary -center">View</a>
            </div>
        </div>
        
    </div>
    <hr style="border: 2px solid gray;">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <div class="well well-lg text-center">
                <h3>Promotion Pitches</h3>
                <p>Want to promote anything, step right up and begin.</p>
                <a href="{{url_for('main.promotion')}}" class="btn btn-primary -center">View</a>
            </div>
        </div>
    </div>
    
</div>
{%endblock%}
<style>
    .row{
        display: flex;
        justify-content: center;
    }
</style>

app/templates/interview.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{%block content%}
<link href="https://fonts.googleapis.com/css?family=Indie+Flower|Ranga" rel="stylesheet">
<div class="jumbotron text-center" style="padding: 100px 25px; font-family: 'Indie Flower', cursive; align-items: center;">
    <h1>Interview Pitches</h1>
</div>
<div class="container" style="font-family: 'Indie+Flower', cursive;">
    <hr>
    <div class="row">
        {{macro.pitchesDisplay(pitches)}}
    </div>
</div>
{%endblock%}

app/templates/interview_pitches.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{%block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
    {%endblock%}

{%block content%}
<link href="https://fonts.googleapis.com/css?family=Indie+Flower|Ranga" rel="stylesheet">
<div class="jumbotron text-center" style="padding: 100px 25px; font-family: 'Indie Flower', cursive; align-items: center;">
    <h1>Interview Pitches</h1>
</div>
<div class="container" style="font-family: 'Indie+Flower', cursive;">
    <hr>
    <div class="row">
        {{macro.displayPitches(pitches)}}
    </div>
</div>
{%endblock%}

app/templates/macros.html
{% macro pitchesDisplay(pitcheslist)%}
    {%for pitch in pitcheslist%}
        <div class="col-xs-12 col-sm-4 col-md-6 mx-auto col-lg-4 review-card">
            <div class="well well-lg">
                <h4>{{pitch.pitch_title}}</h4>
                <p>{{pitch.pitch_content| truncate(100)}}</p>
                <p>Written by:  {{pitch.user.username}} <a href="/pitch/{{pitch.id}}" class="btn btn-primary pull-right">Read</a> </p>
            </div>
        </div>
    {%endfor%}
{%endmacro%}
{%macro displayComments(comments_list)%}
    {%for comment in comments_list%}
        <div class="col-md-12">
            <h5>{{comment.user.username}}</h5>
            <p>{{comment.comment}}</p>
        </div>
    {%endfor%}
{%endmacro%}

app/templates/navbar.html
<div class="navbar navbar-light " role="navigation" style="margin-bottom:0; border-bottom: 1px solid;">
    <div class="container-fluid ">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            
        </div>
        <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav ">
                    <li><a href="/">Home</a></li>
                    <li><a href="{{url_for('main.interview')}}">Interview</a></li>
                    <li><a href="{{url_for('main.product')}}">Product</a></li>
                    <li><a href="{{url_for('main.promotion')}}">Promotion</a></li>
                    <li><a href="{{url_for('main.add_pitch')}}">Create Pitch</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                    <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{current_user.username| capitalize}} <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{{url_for('main.profile',name=current_user.username)}}">Profile</a></li>
                            <li><a href="{{url_for('main.user_pitches',name=current_user.username)}}">My Pitches</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                        </ul>
                    </li>
                    {% else %}
                    <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                </ul>
                {%endif%}
            </div>
    </div>
</div>

app/templates/new_pitch.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
    <div class="container">
        <div class="col-md-12">
            <h3>Create a pitch</h3>
            <hr>
            {{ wtf.quick_form(pitch_form) }}
        </div>

    </div>

{% endblock %}

app/templates/pitch.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
{% import "bootstrap/wtf.html" as wtf %}

{%block styles%}
    {{ super() }}
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower|Ranga" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
{%endblock%}
{%block content%}
<div class="container" style="font-family: 'Indie Flower', cursive;">
    <div class="row">
        <h3>{{pitch.pitch_title}}</h3>
        <hr>
        <p>{{pitch.pitch_content}}</p>
        <span>
        <p>Posted on {{date}} by {{pitch.user.username| capitalize}}</p>
        <a href="/pitch/{{pitch.id}}?like=1">
            <i class="far fa-thumbs-up"></i>
        </a>{{pitch.likes}} <a href="/pitch/{{pitch.id}}?dislike=1">
            <i class="far fa-thumbs-down"></i>
        </a>{{pitch.dislikes}}</span>

    </div>
    <div class="row">
        <h4>Comments</h4>
        <hr>
        {% if current_user.is_authenticated %}
            {{ wtf.quick_form(comment_form) }}
        {%endif%}
        {{macro.displayComments(comments)}}
    </div>

</div>
{%endblock%}

app/templates/product.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}
{%block content%}
<link href="https://fonts.googleapis.com/css?family=Indie+Flower|Ranga" rel="stylesheet">
<div class="jumbotron text-center" style=" padding: 100px 25px; font-family: 'Indie Flower', cursive;">
    <h1>Product Pitches</h1>
</div>
<div class="container" style="font-family: 'Indie+Flower', cursive;">
    <hr>
    <div class="row">
        <div class="col-md-12">
            {{macro.pitchesDisplay(pitches)}}
        </div>
        
    </div>
</div>
{%endblock%}

app/templates/product_pitches.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{%block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
    {%endblock%}

{%block content%}
<link href="https://fonts.googleapis.com/css?family=Indie+Flower|Ranga" rel="stylesheet">
<div class="jumbotron text-center" style=" padding: 100px 25px; font-family: 'Indie Flower', cursive;">
    <h1>Product Pitches</h1>
</div>
<div class="container" style="font-family: 'Indie+Flower', cursive;">
    <hr>
    <div class="row">
        <div class="col-md-12">
            {{macro.displayPitches(pitches)}}
        </div>
        
    </div>
</div>
{%endblock%}

app/templates/profile/pitches.html
{% extends 'base.html'%}
{%import 'macros.html' as macro%}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="thumbnail">
                {% if user.profile_pic_path %}
                <img class="" src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
                {%else%}
                <p>No profile picture</p>
                {% endif %}
            </div>
        </div>
        <h3> {{user.username}} </h3>
        <hr>
        <div class="col-md-9">
            <p>Name: {{user.firstname}} {{user.lastname}} </p>
        </div>
        <div class="row">
            <div class="col-md-12">
              <h3> My Pitches </h3>
              <hr>
               {{macro.pitchesDisplay(pitches)}}
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
    <div class="row">
        
        <div class="col-md-3">
            <div class="thumbnail">
                {% if user.profile_pic_path %}
                <img class="" src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
                {%else%}
                <p>No profile picture</p>
                {% endif %}

                {% if user == current_user %}
                <form action="{{url_for('main.update_pic',name=user.username)}}" method="post" enctype="multipart/form-data">
                    <input type="file" name="photo" class="form-control" required>
                    <input type="submit">
                </form>
                    {% endif %}
            </div>
        </div>
        <div class="col-md-9">
            <p>Name: {{user.firstname}} {{user.lastname}} </p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
          <h3> Bio </h3>
          {% if user.bio %}
            <p> {{user.bio}}</p>
          {%else%}
            <p> {{user.username| capitalize}} has no bio </p>
          {% endif %}

          {% if user == current_user %}
          <a href="{{url_for('main.update_profile',name=user.username)}}">Edit profile</a>
          {% endif %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}

app/templates/promotion.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}
{%block content%}
<link href="https://fonts.googleapis.com/css?family=Indie+Flower|Ranga" rel="stylesheet">
<div class="jumbotron text-center" style="padding: 100px 25px; font-family: 'Indie Flower', cursive;">
    <h1>Promotion Pitches</h1>
</div>
<div class="container" style="font-family: 'Indie+Flower', cursive;">
    <hr>
    <div class="row">
        {{macro.pitchesDisplay(pitches)}}
    </div>
</div>
{%endblock%}

app/templates/promotion_pitches.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{%block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
    {%endblock%}

{%block content%}
<link href="https://fonts.googleapis.com/css?family=Indie+Flower|Ranga" rel="stylesheet">
<div class="jumbotron text-center" style="padding: 100px 25px; font-family: 'Indie Flower', cursive;">
    <h1>Promotion Pitches</h1>
</div>
<div class="container" style="font-family: 'Indie+Flower', cursive;">
    <hr>
    <div class="row">
        {{macro.displayPitches(pitches)}}
    </div>
</div>
{%endblock%}